apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-backend-config
  labels:
    {{- include "todo-chatbot.backendLabels" . | nindent 4 }}
data:
  BETTER_AUTH_URL: {{ .Values.backend.env.BETTER_AUTH_URL | quote }}
  FRONTEND_URL: {{ .Values.backend.env.FRONTEND_URL | quote }}
