apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-backend
  labels:
    {{- include "todo-chatbot.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.backend.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.backendSelectorLabels" . | nindent 4 }}
