apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-frontend
  labels:
    {{- include "todo-chatbot.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.frontend.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.frontendSelectorLabels" . | nindent 4 }}
